### ISSUE TITLE
deploy staging to us-west-2

### ISSUE THREAD

**Issue by lazzarello** [quantstamp/eth-router#37]
Use the new environment variable system to deploy a new staging environment to `us-west-2` , verify it provides connectivity and tear it down.

This is the acceptance criteria to merge `staging` into `master`. Keep in mind that post-deploy "old master" will no longer work with a blockchain host that is located outside of AWS.

Since this is not the primary use-case for this latest milestone, that's fine, though ensuring a blockchain node can be located anywhere is an important feature.

**Comment by lazzarello** [comment]
ref #36

**Comment by lazzarello** [comment]
Need to add stuff in the docs about dependent modules, like py-yaml

```
null_resource.ansible_configure_blockchain (local-exec): Traceback (most recent call last):
null_resource.ansible_configure_proxy (local-exec): Traceback (most recent call last):
null_resource.ansible_configure_blockchain (local-exec):   File "<string>", line 1, in <module>
null_resource.ansible_configure_proxy (local-exec):   File "<string>", line 1, in <module>
null_resource.ansible_configure_blockchain (local-exec): ImportError: No module named yaml
null_resource.ansible_configure_proxy (local-exec): ImportError: No module named yaml
```

**Comment by lazzarello** [comment]
It appears there's some timeout issue with the Ansible provisioner.

```
Error: Error applying plan:

1 error(s) occurred:

* null_resource.ansible_configure_proxy: Error running command 'ansible-playbook --vault-password-file /Users/leeazzarello/Documents/quantstamp/src/eth-router/deploy/terraform/dump_to_txt.sh -i hosts -u ubuntu proxy.yml -e "ssl_hostname=prod.rpc.blockchaindevlabs.com"': exit status 4. Output:  ____________________________________________________________ 
/ PLAY [Install a full ethereum RPC proxy with SSL and token \
\ auth]                                                      /
 ------------------------------------------------------------ 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

 ________________________ 
< TASK [Gathering Facts] >
 ------------------------ 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [54.218.163.0]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 54.218.163.0 port 22: Operation timed out\r\n", "unreachable": true}
	to retry, use: --limit @/Users/leeazzarello/Documents/quantstamp/src/eth-router/deploy/ansible/proxy.retry
 ____________ 
< PLAY RECAP >
 ------------ 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

54.218.163.0               : ok=0    changed=0    unreachable=1    failed=0   



Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by lazzarello** [comment]
This might be related to verifying the SSH hostid. I don't think Ansible takes interactive input.

```
null_resource.ansible_configure_proxy (local-exec):  ________________________
null_resource.ansible_configure_proxy (local-exec): < TASK [Gathering Facts] >
null_resource.ansible_configure_proxy (local-exec):  ------------------------
null_resource.ansible_configure_proxy (local-exec):         \   ^__^
null_resource.ansible_configure_proxy (local-exec):          \  (oo)\_______
null_resource.ansible_configure_proxy (local-exec):             (__)\       )\/\
null_resource.ansible_configure_proxy (local-exec):                 ||----w |
null_resource.ansible_configure_proxy (local-exec):                 ||     ||

The authenticity of host '54.218.163.0 (54.218.163.0)' can't be established.
ECDSA key fingerprint is SHA256:DuFYBQ5wnq2Oi+Di917d1h2v5HfVmR/KRxEwvLJfRa0.
Are you sure you want to continue connecting (yes/no)? module.proxy.aws_eip_association.eip_assoc: Destroying... (ID: eipassoc-03c18e9271848d910)
```

**Comment by lazzarello** [comment]
The following is required for Ansible configuration. Closing.

```
[defaults]
host_key_checking = False
```
